kind = "web"
previewPath = "/"
title = "ASAV Soft Tech"
version = "1.0.0"
id = "artifacts/asav-soft-tech"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24188

[services.development]
run = "pnpm --filter @workspace/asav-soft-tech run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/asav-soft-tech", "run", "build" ]
publicDir = "artifacts/asav-soft-tech/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24188"
BASE_PATH = "/"
